### ISSUE TITLE
Iteração 0 - Feedback

### ISSUE THREAD

**Issue by Lerissonf** [eliezerpedro/Culturally#13]
# - **Iteração 0 - FeedBack**

## - **Histórias de Usuários**

- ### _Atraso na entrega das HUs_ -> não (nota base 10.0)

- ### _Formato "como...eu gostaria... para...._ -> ok

- ### _História bem descrita_ -> -2
	Deixar claro o que um usuário faz ou necessita fazer como parte de sua função de trabalho

## Nota final: 8.0
	10.0 - 2.0 = 8.0

## - **Ata da reunião com cliente**

- ### _Atraso na entrega da ata de reunião com cliente_ -> não (nota base 10.0)

- ### _Participantes da reunião_ -> ok

- ### _Tópicos discutidos_ -> ok

- ### _O que foi definido_ -> ok

- ### _Formato Markdown_ -> ok

## - **Mockups e storyboards**

- ### _Atraso na entrega dos mockups e storyboards_ -> não (nota base 10.0)

- ### _Bem construído_ -> sim

## - **Preenchimento do gitHub**

- ### _Atraso no preenchimento_ -> não (nota base 10.0)

- ### _Nome do projeto_  -> 0,7
	Não deixou explicito no readme.md

- ### _Descrição do Produto_ -> ok

- ### _Justificativa do Projeto_ -> -3
	Vocês não deixaram claro uma justificativa que levaram vocês a realizarem esse projeto no readme.md.

- ### _Especificação do papel de cada membro_ -> ok

- ### _Uso de lable_ -> ok

- ### _Milestones_ -> ok

- ### _Descrição da issue_ -> ok

## Nota final: 6.3
          10.0 - 0.7 - 3.0 = 6.3

## - **Postmortem**

   O modelo presente no repositório serve como exemplo de como o postmortem deve ser feito:
   [Modelo Postmortem](https://github.com/IF977/monitoria-if977-SI/blob/master/Postmortem.md)

- ### _Atraso na entrega do postmortem_ -> não (nota base 10.0)

- ### _Postmortem deve estar em markdown (.md)_ -> ok

- ### _Período da iteração_ -> - ok
    
- ### _O que estava planejado_ -> ok

- ### _O que foi feito_ -> - 0,5
	Esqueceu-se de explicitar quem fez cada atividade, mesmo que esteja explicitado no planejado pode ocorrer o caso de outro componente do time realizar a tarefa, então na próxima não esqueçam de colocar, além disso separe o que foi feito do que não foi feito como mostra o exemplo acima. 

- ### _O que não foi feito_ -> 0,5
	Esqueceu-se de explicitar quem não fez tal atividade, mesmo que esteja explicitado no planejado pode ocorrer o caso de outro componente do time realizar a tarefa, então na próxima não esqueçam de colocar quem não realizou na devida atividade, além disso separe o que foi feito do que não foi feito como mostra o exemplo acima.

- ### _Planejado para próxima iteração_ ->ok

- ### _Lições aprendidas_ -> ok

## Nota final: 9.0
          10.0 - 0.5 - 0.5 = 9.0

**Comment by Lerissonf** [comment]
OBS.: Adicionem a Label de **FeedBack** na cor **verde marca texto** e adicionem a essa issue, não posso fazer isso porque não estou no projeto.

**Comment by gabrieldluca** [comment]
Oi @Lerissonf. Te adicionamos como colaborador e atualizamos a issue. Em breve estarei realizando as correções de acordo com o feedback. No mais, obrigado!
