### ISSUE TITLE
Correção Iteração 3 - Testes TDD, BDD e modelo ER

### ISSUE THREAD

**Issue by ps1312** [eliezerpedro/Culturally#35]
## Testes BDD:

* Não possui nenhum caminho triste -> Possuem caminhos tristes e felizes
* Todos os testes verdes -> Tudo ok.

## Testes TDD:

* Todos os testes verdes -> Não, algumas expectations não foram aprovadas (-2).

![image](https://user-images.githubusercontent.com/19872825/40789691-68924d54-64c9-11e8-9fd3-8e89e81b4da0.png)

* Cobertura de testes -> os testes TDD de vocês tá com uma cobertura muito pequena, é necessário que vocês desenvolvam mais. (-1).

#### Nota TDD: 2
---
## nota final: 7

---

## Modelo ER:

* Pessoal, não encontrei o modelo ER de vocês..

## nota final: 0

**Comment by acl5** [comment]
@ps1312 , nós fizemos o modelo ER há muito tempo! Não sei por que não está aparecendo aqui.

**Comment by acl5** [comment]
<img width="1014" alt="captura de tela 2018-06-02 as 20 02 46" src="https://user-images.githubusercontent.com/23489103/40881571-065c0778-66a0-11e8-8f94-afec4aeac972.png">

**Comment by ps1312** [comment]
Desculpa pessoal, foi uma desatenção minha. O modelo ER de vocês está correto. Atualizei a nota na planilha.
